version: '2'
services:
  app:
    image: openjdk:8-jdk
    working_dir: /app
    volumes:
      - .:/app
    command: /app/build/install/declaratii-anaf/bin/declaratii-anaf
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
