/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on 02.05.2012, 08:55:47
 */
package ajutor;

import java.io.IOException;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author 22276637
 */
public class Ajutor extends javax.swing.JFrame
{
    // private final int w1 = 900;
    // private final int h1 = 600;
    public int stare = 0;
    public static String _newline = System.getProperty("line.separator");

    /** Creates new form Help */
    public Ajutor(String cale)
    {
        initComponents();
        // calculateLocation();
        setTitle("Help DUKIntegrator");
        //setResizable(false);
        jEditorPane1.setEditable(false);
        jEditorPane2.setEditable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        try
        {
            URL index = new URL("file:///" + cale + "Ajutor.html");
            URL contents = new URL("file:///" + cale + "doc/contents.html");
            jEditorPane2.setPage(index);
            jEditorPane1.setPage(contents);
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(rootPane, "Eroare in afisarea continutului fisierelor de Help");
            stare = -1;
        }

        //  getContentPane().add(new JScrollPane(jEditorPane1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        jEditorPane2.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane2HyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(jEditorPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEditorPane1HyperlinkUpdate
        try
        {
            if(evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
            {
                jEditorPane2.setPage(evt.getURL());
            }
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(rootPane, "Link negasit" + _newline + ex.toString());
        }
    }//GEN-LAST:event_jEditorPane1HyperlinkUpdate

    private void jEditorPane2HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEditorPane2HyperlinkUpdate
        try
        {
            if(evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
            {
                jEditorPane2.setPage(evt.getURL());
            }
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(rootPane, "Link negasit" + _newline + ex.toString());
        }
    }//GEN-LAST:event_jEditorPane2HyperlinkUpdate
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
